ifeq ($(COMPILER),ifort)
     FFLAGS = -cpp -c -O2 -stand f08 -real-size 64 -auto-scalar 
     LDFLAGS = -cpp
     DFFLAGS = -g -Wall -traceback
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXXFLAGS = -O2 -std=c++11
     CXXLIBS = -lstdc++ -lgfortran -L$(NETCDFLIB)/lib -lnetcdff
     CXXLDFLAGS =

else ifeq ($(COMPILER),pgf90)
     FFLAGS = -cpp -c -fast -r8
     LDFLAGS = -cpp
     DFFLAGS = -g -traceback -Mbounds
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXXFLAGS = -O2 -mp -std=c++11
     CXXLIBS = -lstdc++ -lgfortran -L$(NETCDFLIB)/lib -lnetcdff
     CXXLDFLAGS =

else
     COMPILER = gfortran
     FFLAGS = -cpp -c -O2 -std=f2008 -fdefault-real-8 -ffpe-trap=invalid,zero,overflow
     LDFLAGS = -cpp
     DFFLAGS = -Og -Wall
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXXFLAGS = -O2 -std=c++11
     CXXLIBS = -lstdc++ -lgfortran
     CXXLDFLAGS = 
endif

FLIBS = -L$(NETCDFLIB)/lib -lnetcdff
FINCL = -I$(NETCDFINC)/include
