ifeq ($(COMPILER),ICC)
     FFLAGS = -O2 -stand f08 -real-size 64 -auto-scalar
     LDFLAGS = -cpp
     DFFLAGS = -g -traceback -check all -warn all
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXXFLAGS = -O2 -std=c++11
     CXXLIBS = -lifcore
     CXXLDFLAGS =

else ifeq ($(COMPILER),PGC)
     FFLAGS = -fast -r8
     LDFLAGS = -cpp
     DFFLAGS = -g -traceback -Mbounds
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXXFLAGS = -O2 -mp -std=c++11
     CXXLIBS = -lstdc++ -lgfortran
     CXXLDFLAGS =

else
     COMPILER = gfortran
     FFLAGS = -O2 -std=f2008 -fdefault-real-8 -ffpe-trap=invalid,zero,overflow
     LDFLAGS = -cpp
     DFFLAGS = -Og -Wall
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXXFLAGS = -O2 -std=c++11
     CXXLIBS = -lstdc++ -lgfortran
     CXXLDFLAGS = 
endif

FLIBS = -L$(NETCDFLIB)/lib -lnetcdff
FINCL = -I$(NETCDFINC)/include
