ifeq ($(FC),ifort)
     FFLAGS = -cpp -c -O2 -stand f08 -real-size 64 -ftz -auto-scalar -align dcommons 
     LDFLAGS = -cpp
     DFFLAGS = -g -Wall -traceback
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXX = icc
     CXXFLAGS = -O2 -std=c++11
     CXXLIBS = -lstdc++ -lgfortran -L$(NETCDF_DIR)/lib -lnetcdff
     CXXLDFLAGS =

else ifeq ($(FC),pgf90)
     FFLAGS = -cpp -c -fast -r8
     LDFLAGS = -cpp
     DFFLAGS = -g -traceback -Mbounds
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXX = pgc++
     CXXFLAGS = -O2 -mp -std=c++11
     CXXLIBS = -lstdc++ -lgfortran -L$(NETCDF_DIR)/lib -lnetcdff
     CXXLDFLAGS =

else
     FC = gfortran
     FFLAGS = -cpp -c -O2 -std=f2008 -m64 -ffpe-trap=invalid,zero,overflow -fno-range-check -fdollar-ok
     LDFLAGS = -cpp
     DFFLAGS = -Og -Wall
     SFFLAGS = -fpic
     SLDFLAGS = -shared
     CXX = g++
     CXXFLAGS = -O2 -m64 -std=c++11
     CXXLIBS = -lstdc++ -lgfortran
     CXXLDFLAGS = 
endif

FLIBS = -L$(NETCDF_DIR)/lib -lnetcdff
FINCL = -I$(NETCDF_DIR)/include
