name: EZCDF CI

on: [push]

jobs:
  buildtest:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
	sudo apt-get install -y gfortran
        sudo apt-get install -y libnetcdf-dev libnetcdff-dev
    - name: build
      run: |
        export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
        cd src
        make
    - name: eztest
      run: ./eztest > eztest.out && diff -w eztest.out ../ref/eztest/eztest.out
    - name: eztest2
      run: ./eztest2 > eztest2.out && diff -w eztest2.out ../ref/eztest2/eztest2.out
