name: EZCDF CI

on: [push]

jobs:
  buildtest:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        sudo apt-get install -y gfortran
        sudo apt-get install -y libnetcdf-dev libnetcdff-dev
    - name: build
      run: |
        export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
        cd src
        make
        make install
    - name: eztest
      run: bin/eztest > eztest.ref && diff -w eztest.ref ref/eztest/eztest.ref
    - name: eztest2
      run: bin/eztest2 > eztest2.ref && diff -w eztest2.ref ref/eztest2/eztest2.ref
